-- MySQL Script generated by MySQL Workbench
-- Чтв 02 сен 2021 22:33:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`authors_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`authors_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` ENUM('AUTHOR', 'CO-AUTHOR') NOT NULL DEFAULT 'AUTHOR',
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`books_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books_authors` (
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `author_role_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`, `author_role_id`),
  INDEX `fk_book_authors_author1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_book_authors_role1_idx` (`author_role_id` ASC) VISIBLE,
  CONSTRAINT `author_role_id`
    FOREIGN KEY (`author_role_id`)
    REFERENCES `library`.`authors_roles` (`id`),
  CONSTRAINT `fk_book_authors_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `library`.`authors` (`id`),
  CONSTRAINT `fk_book_authors_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`books` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`books_copies_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books_copies_statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('ISSUED', 'AVAILABLE', 'DELETED', 'LOST') NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`books_copies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books_copies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT '2',
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `book_id`, `status`),
  INDEX `fk_book_copies_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_book_copies_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_book_copies_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`books` (`id`),
  CONSTRAINT `fk_books_copies_status`
    FOREIGN KEY (`status`)
    REFERENCES `library`.`books_copies_statuses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`orders_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`orders_statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('PENDING', 'PROCESSED', 'CLOUSED') NOT NULL DEFAULT 'PENDING',
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`users_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` ENUM('MANAGER', 'READER') NOT NULL DEFAULT 'READER',
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `registration_date` DATE NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `user_role_id` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_role_id`),
  INDEX `user_role_id_idx` (`user_role_id` ASC) VISIBLE,
  CONSTRAINT `user_role_id`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `library`.`users_roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `processed_date` DATE NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `return_date` DATE NULL DEFAULT NULL,
  `book_copy_id` INT NULL DEFAULT NULL,
  `order_status_id` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `order_status_id_idx` (`order_status_id` ASC) VISIBLE,
  INDEX `book_copy_id_idx` (`book_copy_id` ASC) VISIBLE,
  CONSTRAINT `book_copy_id`
    FOREIGN KEY (`book_copy_id`)
    REFERENCES `library`.`books_copies` (`id`),
  CONSTRAINT `order_status_id`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `library`.`orders_statuses` (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `library`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
